---
- name: Remove dangling Docker images
  hosts: all
  become: yes
  tasks:
    - name: Remove all dangling Docker images
      shell: docker rmi $(docker images -f dangling=true -qa)
      ignore_errors: yes
