-
  hosts: all
  become: yes
  tasks:
    - name: Update Package on Debian Machine
      command: echo "Host is Accessible"

      # To Check Distribution
    - name: Debug ansible_distribution
      debug:
        var: ansible_distribution
