---
- name: Enforce Strict Password Policy
  hosts: all
  become: yes
#  vars:
#    ansible_become_pass: 123                   # Set Sudo Password if required
  tasks:
    - name: Install PAM tools (Debian/Ubuntu)
      apt:
        name: libpam-pwquality
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install PAM tools (CentOS/RHEL)
      yum:
        name: pam_pwquality
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Configure password policy
      copy:
        src: pwquality.conf
        dest: /etc/security/pwquality.conf
        owner: root
        group: root
        mode: '0644'
      notify: reload PAM configuration

    - name: Configure password policy
      copy:
        src: pwquality.conf
        dest: /etc/security/pwquality.conf
        owner: root
        group: root
        mode: '0644'
      notify: reload PAM configuration

    - name: Update access.conf (optional)
      copy:
        src: access.conf
        dest: /etc/security/access.conf
        owner: root
        group: root
        mode: '0644'

  handlers:
    - name: reload PAM configuration
      become: yes
      command: pam-auth-update --force

