---
- name: Collect Stats
  hosts: all
  become: yes
  ignore_unreachable: true
  ansible_become_method: su
  vars:
    remote_server: "{{ lookup('env', 'second_remote_server') }}"
    remote_user: "{{ lookup('env', 'second_remote_user') }}"
    remote_path: "{{ lookup('env', 'remote_path') }}"
    remote_password: "{{ lookup('env', 'second_remote_password') }}"
    ansible_become: true
    ansible_become_user: "{{ ansible_become_user }}"
    ansible_become_password: "{{ ansible_become_password }}"
    
  tasks:
    - name: Get the primary IP address using hostname and awk
      shell: "hostname -I | awk '{print $1}'"
      register: primary_ip
  
    # - name: Debug the primary IP address
    #   debug:
    #     msg: "The primary IP address is {{ primary_ip.stdout }}"
    
    # - name: Example task with sudo
    #   command: whoami
    #   become: true
    #   become_user: "{{ ansible_become_user }}"
    #   become_method: sudo
      
    # - name: Get the first network interface IP address
    #   ansible.builtin.command: hostname -I | awk '{print $1}'
    #   become: true
    #   become_user: "{{ ansible_become_user }}"
    #   become_method: sudo
    #   register: first_interface_ip

    - name: Append IP address to the start of each file
      ansible.builtin.shell: |
       for file in message_count/*; do
         echo "{{ primary_ip.stdout }}" | cat - "$file" > temp && mv temp "$file"
       done
      become: true
      become_user: root
#      args:
#        chdir: /path/to/your/working/directory

    #- name: Copy files from first remote server to second remote server
    #  ansible.builtin.shell: |
    #    scp -r message_count/* {{ remote_user }}@{{ remote_server }}:{{ remote_path }}
