- 
  hosts: all
  become: yes
  ignore_unreachable: true
  tasks:

    - name: Restart service "node_exporter"
      service: 
       name: "{{ item }}"
       state: restarted 
       enabled: yes
      with_items:
       - node_exporter
      ignore_errors: yes
