- 
  hosts: all 
  connection: "local"
  gather_facts: false
  become: yes
  tasks:
    
    - name: copy NODE_Exporter Binary File
      copy: 
       src: ./nodeBinary/node_exporter
       dest: /usr/local/bin/
       owner: root
       mode: a+x
       force: yes
       
    - name: copy Service File
      copy: 
       src: ./node_exporter.service
       dest: /etc/systemd/system/
       owner: root
       force: yes

    - name: "Create user accounts and add users to groups"
      user:
        name: node_exporter
        state: present
        create_home: no

    - name: Restart service "node_exporter"
      #shell: systemctl start docke
      service: 
       name: "{{ item }}"
       state: restarted 
       enabled: yes
      with_items:
       - node_exporter
      ignore_errors: yes
