# - 
#   hosts: all
#   user: vaival
#   become: yes
#   become_user: root
#   tasks:

---
- name: Test write permissions
  hosts: all
  become: yes

  tasks:
    - name: Create a test file
      file:
        path: /etc/sudoers.d/test_file
        state: touch
    # - name: copy Sudoers File
    #   copy: 
    #    src: ./ubuntu_soduers_rules
    #    dest: /etc/sudoers.d/
    #    owner: root
    #    mode: '0440'
       force: yes
