---
- name: Test write permissions
  hosts: all
  become: yes
  become_user: root
  
  tasks:
    - name: Create a test file
      file:
        path: /tmp/test_file
        state: touch
    - name: Copy File
      copy:
        src: /tmp/test_file
        dst: /etc/sudoers.d/
        owner: root
        mode: '0440'
